name: Update Components

on:
  schedule:
    # Ejecutar todos los lunes a las 09:00 UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
  push:
    paths:
      - 'components_config.json'
      - 'update_components.py'

jobs:
  check-updates:
    runs-on: ubuntu-latest
    outputs:
      updates-available: ${{ steps.check.outputs.updates-available }}
      updates-json: ${{ steps.check.outputs.updates-json }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Check for updates
      id: check
      run: |
        python update_components.py --check > check_output.txt 2>&1
        if grep -q "Actualizaciones disponibles" check_output.txt; then
          echo "updates-available=true" >> $GITHUB_OUTPUT
          # Extraer información de actualizaciones para el PR
          python -c "
        import json
        from update_components import ComponentUpdater
        updater = ComponentUpdater()
        updates = updater.check_for_updates()
        print('updates-json=' + json.dumps(updates))
        " >> $GITHUB_OUTPUT
        else
          echo "updates-available=false" >> $GITHUB_OUTPUT
        fi
        cat check_output.txt

  update-components:
    needs: check-updates
    if: needs.check-updates.outputs.updates-available == 'true'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Update components
      run: |
        python update_components.py
        
    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "has-changes=false" >> $GITHUB_OUTPUT
        else
          echo "has-changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.changes.outputs.has-changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: |
          🤖 Actualización automática de componentes
          
          Componentes actualizados:
          ${{ needs.check-updates.outputs.updates-json }}
        title: "🤖 Actualización automática de componentes"
        body: |
          ## 🔄 Actualización Automática de Componentes
          
          Este PR fue creado automáticamente para actualizar los componentes de Lovelace a sus últimas versiones.
          
          ### Componentes Actualizados
          
          ```json
          ${{ needs.check-updates.outputs.updates-json }}
          ```
          
          ### ✅ Verificaciones Realizadas
          - [x] Descarga exitosa de archivos
          - [x] Verificación de integridad de archivos
          - [x] Actualización de información de versiones
          
          ### 📋 Próximos Pasos
          
          1. Revisa los cambios en los archivos
          2. Verifica que no haya breaking changes en los componentes originales
          3. Prueba los componentes en tu instancia de Home Assistant
          4. Merge este PR si todo funciona correctamente
          
          ---
          
          **Nota**: Este PR se generó automáticamente el ${{ steps.date.outputs.date }}
        branch: update-components-${{ github.run_number }}
        delete-branch: true

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT

  notify-no-updates:
    needs: check-updates
    if: needs.check-updates.outputs.updates-available == 'false'
    runs-on: ubuntu-latest
    
    steps:
    - name: No updates notification
      run: |
        echo "✅ Todos los componentes están actualizados. No se requieren cambios."